
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/?useSSL=false
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
insert-data: true
service:
  type: Crud Service Injected By Yml Properties Dev

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
insert-data: false
service:
  type: Crud Service Injected By Yml Properties Prod
